export const OPEN_SERVICE_MODAL = 'OPEN_SERVICE_MODAL';
export const CLOSE_SERVICE_MODAL = 'CLOSE_SERVICE_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const SET_CURRENT_SERVICE = 'SET_CURRENT_SERVICE';
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
